#pragma once

/* ----- THE FOLLOWING DEFINES ARE FOR CONFIGURING THE PROFILER ------*/

/* CHANGE THIS VALUE TO CHANGE THE FREQUENCY OF SAMPLING */
#define SAMPLING_PERIOD 120

/* CHANGE THIS VALUE TO CHANGE WHAT PD TO TRACK (WE NEED TO ACCESS THE TCB OF
A PD TO TRACK PC) */
#define PD_ID 0

/* CHANGE THIS VALUE TO CHANGE WHAT COUNTER WE WILL SAMPLE ON.
0 = CNT0
1 = CNT1
2 = CNT2
3 = CNT3
4 = CNT4
5 = CNT5
6 = CYCLE COUNTER */
#define IRQ_COUNTER 2
